import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
function App(){const[t,setT]=useState(localStorage.getItem('token')||''),[l,setL]=useState({email:'',password:''}),[s,setS]=useState([]),[q,setQ]=useState(''),[a,setA]=useState(''),[f,setF]=useState({name:'',email:'',course:'BTech CSE',year:2,cgpa:'',phone:''});
async function login(e){e.preventDefault();let r=await fetch(API+'/api/auth/login-json',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(l)}),d=await r.json();if(r.ok){localStorage.setItem('token',d.access_token);setT(d.access_token)}else alert(d.detail)}
async function load(){let r=await fetch(API+'/api/students/',{headers:{Authorization:'Bearer '+t}});if(r.ok)setS(await r.json())}useEffect(()=>{if(t)load()},[t]);
async function add(e){e.preventDefault();let r=await fetch(API+'/api/students/',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+t},body:JSON.stringify({...f,year:+f.year,cgpa:f.cgpa?+f.cgpa:null})});if(r.ok){setF({...f,name:'',email:'',cgpa:'',phone:''});load()}else alert((await r.json()).detail)}
async function chat(e){e.preventDefault();let r=await fetch(API+'/api/chatbot/chat',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+t},body:JSON.stringify({message:q})}),d=await r.json();setA(d.response||d.detail)}
if(!t)return <main className="center"><form className="card"onSubmit={login}><h1>Student Portal</h1><label>Email</label><input type="email"placeholder="Enter your email"value={l.email}onChange={e=>setL({...l,email:e.target.value})}required/><label>Password</label><input type="password"placeholder="Enter your password"value={l.password}onChange={e=>setL({...l,password:e.target.value})}required/><button>Login</button></form></main>;
return <main><header><h1>Student Database System</h1><button onClick={()=>{localStorage.removeItem('token');setT('')}}>Logout</button></header><div className="grid"><form className="card"onSubmit={add}><h2>Add Student</h2>{['name','email','course','year','cgpa','phone'].map(k=><input key={k}placeholder={k}value={f[k]}onChange={e=>setF({...f,[k]:e.target.value})}required={['name','email','course','year'].includes(k)}/>)}<button>Add Student</button></form><form className="card"onSubmit={chat}><h2>AI Assistant</h2><textarea value={q}onChange={e=>setQ(e.target.value)}placeholder="Find students in BTech CSE..."/><button>Ask Gemini</button><p>{a}</p></form></div><section className="card"><h2>Students</h2><table><thead><tr><th>ID</th><th>Name</th><th>Email</th><th>Course</th><th>Year</th><th>CGPA</th></tr></thead><tbody>{s.map(x=><tr key={x.id}><td>{x.id}</td><td>{x.name}</td><td>{x.email}</td><td>{x.course}</td><td>{x.year}</td><td>{x.cgpa??'-'}</td></tr>)}</tbody></table></section></main>}
createRoot(document.getElementById('root')).render(<App/>);
